### ISSUE TITLE
Learning JavaScript

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#128]
[Not An Imposter: Fighting Front-End Fatigue – Smashing Magazine](https://www.smashingmagazine.com/2016/11/not-an-imposter-fighting-front-end-fatigue/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)

**Comment by rogerxu** [comment]
## Reading List

[the new code – A Complete Web Developer Reading List](http://thenewcode.com/1203/A-Complete-Web-Developer-Reading-List)

[thedaviddias/Resources-Front-End-Beginner: 💯 The most essential list of resources for Front-End beginners (🇺🇸 🇬🇧 & 🇫🇷)](https://github.com/thedaviddias/Resources-Front-End-Beginner)

**Comment by rogerxu** [comment]
## Learn ECMAScript

[JS: The Right Way](http://jstherightway.org/)

[ES6 for Everyone — The best way to learn modern ES6 JavaScript](https://es6.io/)

[getify/You-Dont-Know-JS: A book series on JavaScript. @YDKJS on twitter.](https://github.com/getify/You-Dont-Know-JS)

[mqyqingfeng/Blog: 冴羽写博客的地方，预计写四个系列：JavaScript深入系列、JavaScript专题系列、ES6系列、React系列。](https://github.com/mqyqingfeng/Blog)

[Exploring JS: JavaScript books for programmers](https://exploringjs.com/)

**Comment by rogerxu** [comment]
## Study Plan

- [x] [From Zero to Front-end Hero (Part 1)](https://medium.freecodecamp.com/from-zero-to-front-end-hero-part-1-7d4f7f0bff02)
- [x] [From Zero to Front-end Hero (Part 2)](https://medium.freecodecamp.org/from-zero-to-front-end-hero-part-2-adfa4824da9b)
- [x] [Not An Imposter: Fighting Front-End Fatigue](https://www.smashingmagazine.com/2016/11/not-an-imposter-fighting-front-end-fatigue)
- [x] [The Practical Guide to Becoming a Professional Web Developer](https://medium.freecodecamp.com/the-practical-guide-to-becoming-a-professional-web-developer-2f255bc25c90)
- [x] [A Study Plan To Cure JavaScript Fatigue – freeCodeCamp](https://medium.freecodecamp.com/a-study-plan-to-cure-javascript-fatigue-8ad3a54f2eb1)

**Comment by rogerxu** [comment]
## Roadmap

[kamranahmedse/developer-roadmap: Roadmap to becoming a web developer in 2020](https://github.com/kamranahmedse/developer-roadmap)

### 2018

[Modern Frontend Developer in 2018 – tajawal – Medium](https://medium.com/tech-tajawal/modern-frontend-developer-in-2018-4c2072fa2b9c)

**Comment by rogerxu** [comment]
# Study Plan

[kamranahmedse/developer-roadmap: Roadmap to becoming a web developer in 2017](https://github.com/kamranahmedse/developer-roadmap)

**Comment by rogerxu** [comment]
## Exercises

- [ ] [The secret to being a top developer is building things! Here’s a list of fun apps to build!](https://medium.freecodecamp.org/the-secret-to-being-a-top-developer-is-building-things-heres-a-list-of-fun-apps-to-build-aac61ac0736c)
- [ ] [Want to be a top developer? You should build things. Here’s another list to get you started.](https://medium.freecodecamp.org/the-secret-to-being-a-top-developer-is-building-things-d3d058e4e472)
- [ ] [The Complete JavaScript Course: Build a Real-World Project | Udemy](https://www.udemy.com/the-complete-javascript-course/?siteID=QZaBth_yPOQ-6DJzpOuHDLk8nt_7ENhXow&LSNPUBID=QZaBth%2FyPOQ)

**Comment by rogerxu** [comment]
## Book

[我的职业是前端工程师](http://ued.party/)

[Book Tree - Developer进阶书单](http://phodal.github.io/booktree/)

**Comment by rogerxu** [comment]
## Knowledge Base

[Web Fundamentals  |  Google Developers](https://developers.google.com/web/fundamentals/)

[Front-end Developer Handbook 2019 - Learn the entire JavaScript, CSS and HTML development practice!](https://frontendmasters.com/books/front-end-handbook/2019/)

[ouvens/frontend-system-map: init](https://github.com/ouvens/frontend-system-map)

[foru17/front-end-collect: 分享自己长期关注的前端开发相关的优秀网站、博客、以及活跃开发者](https://github.com/foru17/front-end-collect)

**Comment by rogerxu** [comment]
[Introduction · Front-End Developer Handbook 2018](https://frontendmasters.com/books/front-end-handbook/2018/)

**Comment by rogerxu** [comment]
## Blog

- [W3cplus前端网｜引领web前沿，打造前端精品教程](https://www.w3cplus.com/)
- [张鑫旭-鑫空间-鑫生活](https://www.zhangxinxu.com/wordpress/)
