### ISSUE TITLE
你一定爱读的极简欧洲史

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#141]
[你一定爱读的极简欧洲史 (豆瓣)](https://book.douban.com/subject/5366248/)

引言　历史，带领我们更贴近人生

### Part 1 欧洲，是个混合体

- [x] 第一章　从希腊说起，讲到日耳曼 ——古典时期到中世纪
- [x] 第二章　神性到理性，科学到浪漫 ——近代欧洲
- [x] 间奏篇　古典情怀今犹在

### Part 2 迈入文明

- [x] 第三章　争战一千年
- [x] 第四章　民主意识，这样开始的
- [x] 第五章　有国王的民主，没国王的极权
- [x] 第六章　皇帝和教宗到底谁大？
- [x] 第七章　语言：从两种变几十种
- [x] 第八章　平民百姓的生活面貌

结语　欧洲，为什么可以抢第一？
