### ISSUE TITLE
Frontend Technology

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#21]
List of frontend technology

**Comment by rogerxu** [comment]
## HTML

- [ ] HTML

**Comment by rogerxu** [comment]
## CSS

- [ ] CSS 2.0
- [ ] CSS 3.0

### Pre-processor

- [ ] LESS
- [ ] Sass
- [ ] SCSS

**Comment by rogerxu** [comment]
## Testing

## Code Quality
- [x] ESLint
- [x] stylelint
- [ ] Istanbul

### Unit Test
- [x] QUnit
- [ ] Jasmine
- [x] Mocha
- [x] Chai
- [x] Sinon.JS

### Functional Test
- [ ] OPA5

### Test Automation
- [ ] Selenium
- [x] WebDriver
- [ ] Karma Runner
- [x] PhantomJS

### Performance Test
- [ ] JSPerf
- [ ] YSlow 35 Rules
- [ ] PageSpeed
- [ ] HttpWatch
- [ ] DynaTrace's Ajax

**Comment by rogerxu** [comment]
## UX

### Usability

### Accessibility

**Comment by rogerxu** [comment]
## SEO

**Comment by rogerxu** [comment]
## Server-side Programming

- [ ] Express.js

**Comment by rogerxu** [comment]
## JavaScript

### Language
- [ ] ES5
- [x] ES6
- [x] ES2016+
- [ ] CoffeeScript
- [ ] TypeScript
- [ ] elm

### Features
- [x] Prototype
- [x] Closure
- [ ] Functional Programming
- [ ] Anonymous Function
- [ ] Callback

**Comment by rogerxu** [comment]
## Editor
- [ ] Vim
- [x] Notepad++
- [x] Sublime Text 3
- [x] Atom
- [ ] WebStorm
- [x] Eclipse

**Comment by rogerxu** [comment]
## Version Control
- [x] Git
- [ ] Mercurial
- [ ] Perforce
- [ ] SVN

### Project Host
- [x] Gerrit
- [x] GitHub
- [ ] GitLab

**Comment by rogerxu** [comment]
## Security

- [ ] CSRF
- [ ] XSS

**Comment by rogerxu** [comment]
## Tools

- [ ] ESLint
- [ ] CSSLint
- [ ] YUICompressor
- [ ] JSMin

**Comment by rogerxu** [comment]
## Browser

- Internet Explorer (Trident)
- Microsoft Edge
- Google Chrome (Blink)
- Mozilla Firefox (Gecko)
- Safari (WebKit)
- Opera (Blink)

**Comment by rogerxu** [comment]
## Debugger
- [ ] IE Dev Tools
- [ ] Firebug
- [x] Chrome Dev Tools

### Network Tools
- [ ] PostMan
- [ ] Fiddler
- [ ] WireShark

**Comment by rogerxu** [comment]
## Deployment

### Transpiler
- [x] Babel
- [ ] WebAssembly

### Compression
- [ ] YUI Compressor
- [ ] Google Closure Complier
- [ ] UglifyJS

### Task Runner
- [ ] make
- [ ] Ant
- [x] Maven
- [ ] Grunt
- [ ] Gulp

**Comment by rogerxu** [comment]
## Module Manager

### Specification

- [x] CommonJS
- [x] AMD

### Module Manager

- [x] npm
- [x] Bower
- [ ] jspm

### Module Loader

- [x] Require.js

### Module Bundler

- [ ] Browserify - bundle dependencies to files that can be run in the browser
- [x] Webpack
- [ ] SystemJS

**Comment by rogerxu** [comment]
## JavaScript Frameworks

[History of JavaScript Frameworks (programmingsoup.com)](https://programmingsoup.com/history-of-javascript-frameworks)

### Library
- [ ] jQuery
- [ ] Underscore
- [ ] D3.js
- [ ] Lodash

### Framework
- [ ] Dojo
- [ ] SAPUI5
  - [ ] Fiori
  - [ ] Fiori Launchpad
  - [x] Smart Template
- [ ] Angular 2
- [ ] React
  - [x] JSX
  - [x] React DOM
  - [ ] react-router
  - [x] Flux
  - [x] Redux
- [x] Vue.js
  - [x] vue-router
  - [x] vuex

**Comment by rogerxu** [comment]
## ECMAScript 5

**Comment by rogerxu** [comment]
## ECMAScript 6

## JavaScript

### Language

- [ ] ES5
- [ ] ES6
- [ ] ES2016+
- [ ] CoffeeScript
- [ ] TypeScript
- [ ] elm

### Features

- [ ] Prototype
- [ ] Closure
- [ ] Functional Programming
- [ ] Anonymous Function
- [ ] Callback

### ES5 Features

- [ ] Object/array literal extensions
  - [x] Trailing commas in object literals
  - [x] Trailing commas in array literals
  - [ ] Reserved words as property names
- [ ] Object static methods
  - [ ] Object.keys 
  - [ ] Object.getOwnPropertyNames
- [ ] Array methods
  - [ ] Array.isArray
  - [ ] Array.prototype.indexOf
  - [ ] Array.prototype.lastIndexOf
  - [ ] Array.prototype.every
  - [ ] Array.prototype.some
  - [ ] Array.prototype.forEach
  - [ ] Array.prototype.map
  - [ ] Array.prototype.filter
  - [ ] Array.prototype.reduce
  - [ ] Array.prototype.reduceRight

### ES6 Features

#### Optimisation

- [ ] proper tail calls (tail call optimisation)

#### Syntax

- [x] default function parameters
- [x] rest parameters
- [x] spread (...) operator
- [x] object literal extensions
- [ ] for..of loops
- [ ] octal and binary literals
- [x] template literals
- [x] RegExp "y" and "u" flags
- [x] destructuring.declarations
- [x] destructuring.assignment
- [x] destructuring.parameters
- [x] Unicode code point escapes
- [ ] new.target

#### Bindings

- [x] const
- [x] let
- [x] block-level function declaration

#### Functions

- [x] arrow functions
- [ ] class
- [ ] super
- [ ] generators

#### Built-ins

- [ ] Promise
- [ ] Symbol

#### Built-in extensions

- [x] Object static methods
  - [x] Object.assign
  - [x] Object.is
  - [x] Object.getOwnPropertySymbols
  - [x] Object.setPrototypeOf
- [x] function "name" property
- [x] String static methods
  - [x] String.raw
  - [x] String.fromCodePoint
- [x] String.prototype methods
  - [x] String.prototype.codePointAt
  - [x] String.prototype.normalize 
  - [x] String.prototype.repeat
  - [x] String.prototype.startsWith
  - [x] String.prototype.endsWith
  - [x] String.prototype.includes
- [x] RegExp.prototype properties
- [x] Array static methods
  - [x] Array.from
  - [x] Array.of
- [x] Array.prototype methods
  - [x] Array.prototype.copyWIthin
  - [x] Array.prototype.find
  - [x] Array.prototype.findIndex
  - [x] Array.prototype.keys
  - [x] Array.prototype.values
  - [x] Array.prototype.entries
- [x] Number properties
  - [x] Number.isFinite
  - [x] Number.isInteger
  - [x] Number.isSafeInteger
  - [x] Number.isNaN
  - [x] Number.EPSILON
- [x] Math methods
- [ ] Date.prototype

#### Subclassing

- [ ] Array is subclassable

#### Misc

- [ ] prototype of bound functions

### ES2016+ Features

#### 2016 features

- [ ] exponentiation (**) operator
- [x] Array.prototype.includes

#### 2017 features

- [ ] Object.values
- [ ] Object.entries
- [x] String padding
  - [x] String.prototype.padStart
  - [x] String.prototype.padEnd
- [x] trailing commas in function syntax
- [ ] async functions

### next

#### Candidate (stage 3)

- [ ] object rest properties
- [ ] object spread properties
- [ ] global

#### Strawman (stage 0)

- [ ] bind (::) operator

### Browser API

- [ ] XMLHttpRequest
- [ ] Fetch API

**Comment by rogerxu** [comment]
##  ECMAScript 2016+

### Features

- [ ] Prototype
- [ ] Closure
- [ ] Functional Programming
- [ ] Anonymous Function
- [ ] Callback

### ES5 Features

- [ ] Object/array literal extensions
  - [x] Trailing commas in object literals
  - [x] Trailing commas in array literals
  - [ ] Reserved words as property names
- [ ] Object static methods
  - [ ] Object.keys 
  - [ ] Object.getOwnPropertyNames
- [ ] Array methods
  - [ ] Array.isArray
  - [ ] Array.prototype.indexOf
  - [ ] Array.prototype.lastIndexOf
  - [ ] Array.prototype.every
  - [ ] Array.prototype.some
  - [ ] Array.prototype.forEach
  - [ ] Array.prototype.map
  - [ ] Array.prototype.filter
  - [ ] Array.prototype.reduce
  - [ ] Array.prototype.reduceRight

### ES6 Features

#### Optimisation

- [ ] proper tail calls (tail call optimisation)

#### Syntax

- [x] default function parameters
- [x] rest parameters
- [x] spread (...) operator
- [x] object literal extensions
- [ ] for..of loops
- [ ] octal and binary literals
- [x] template literals
- [x] RegExp "y" and "u" flags
- [x] destructuring.declarations
- [x] destructuring.assignment
- [x] destructuring.parameters
- [x] Unicode code point escapes
- [ ] new.target

#### Bindings

- [x] const
- [x] let
- [x] block-level function declaration

#### Functions

- [x] arrow functions
- [ ] class
- [ ] super
- [ ] generators

#### Built-ins

- [ ] Promise
- [ ] Symbol

#### Built-in extensions

- [x] Object static methods
  - [x] Object.assign
  - [x] Object.is
  - [x] Object.getOwnPropertySymbols
  - [x] Object.setPrototypeOf
- [x] function "name" property
- [x] String static methods
  - [x] String.raw
  - [x] String.fromCodePoint
- [x] String.prototype methods
  - [x] String.prototype.codePointAt
  - [x] String.prototype.normalize 
  - [x] String.prototype.repeat
  - [x] String.prototype.startsWith
  - [x] String.prototype.endsWith
  - [x] String.prototype.includes
- [x] RegExp.prototype properties
- [x] Array static methods
  - [x] Array.from
  - [x] Array.of
- [x] Array.prototype methods
  - [x] Array.prototype.copyWIthin
  - [x] Array.prototype.find
  - [x] Array.prototype.findIndex
  - [x] Array.prototype.keys
  - [x] Array.prototype.values
  - [x] Array.prototype.entries
- [x] Number properties
  - [x] Number.isFinite
  - [x] Number.isInteger
  - [x] Number.isSafeInteger
  - [x] Number.isNaN
  - [x] Number.EPSILON
- [x] Math methods
- [ ] Date.prototype

#### Subclassing

- [ ] Array is subclassable

#### Misc

- [ ] prototype of bound functions

### ES2016+ Features

#### 2016 features

- [ ] exponentiation (**) operator
- [x] Array.prototype.includes

#### 2017 features

- [ ] Object.values
- [ ] Object.entries
- [x] String padding
  - [x] String.prototype.padStart
  - [x] String.prototype.padEnd
- [x] trailing commas in function syntax
- [ ] async functions

### next

#### Candidate (stage 3)

- [ ] object rest properties
- [ ] object spread properties
- [ ] global

#### Strawman (stage 0)

- [ ] bind (::) operator

### Browser API

- [ ] XMLHttpRequest
- [ ] Fetch API

**Comment by rogerxu** [comment]
## SAPUI5

**Comment by rogerxu** [comment]
## HTTP

- [ ] HTTP 1.0
- [ ] HTTP 1.1
- [ ] HTTPS
- [ ] SPDY
- [ ] HTTP/2

**Comment by rogerxu** [comment]
## Browser API

- [ ] XMLHttpRequest
- [ ] Fetch API
